server:
  port: 8888
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          # enabled：默认为false，设置为true表明spring cloud gateway开启服务发现和路由的功能，
          # 网关自动根据注册中心的服务名为每个服务创建一个router，将以服务名开头的请求路径转发到对应的服务
          # 商业开发中，enabled一般不设置，使用默认值false。避免不必要的自动转发规则。
          enabled: false
          # lowerCaseServiceId：启动 locator.enabled=true 自动路由时，路由的路径默认会使用大写ID，
          # 若想要使用小写ID，可将lowerCaseServiceId设置为true
          lower-case-service-id: true
      #路由规则
      routes:
        - id: cloud-api
          uri: lb://cloud-api
          predicates:
            - Path=/cloud-api/**
          filters:
            - RewritePath=/cloud-api/(?<segment>.*), /$\{segment}

        - id: cloud-test
          uri: lb://cloud-test
          predicates:
            - Path=/cloud-test/**
          filters:
            - RewritePath=/cloud-test/(?<segment>.*), /$\{segment}
